select ename from emp
where empno in (select mgr from emp
where ename IN ('SMITH'));


SELECT DNAME FROM DEPT
WHERE DEPTNO IN (SELECT DEPTNO FROM EMP 
WHERE EMPNO IN (SELECT MGR FROM EMP WHERE 
ENAME IN ('ALLEN')));


SELECT * FROM EMP 
WHERE MGR IN (SELECT EMPNO FROM EMP
WHERE ENAME IN ('ALLEN'));


SELECT ENAME FROM EMP
WHERE MGR IN (SELECT MGR FROM EMP
WHERE ENAME IN ('ALLEN'));


